---

## NAME2INT
- name: test name2int
  name2int:
    name: "test"
  register: hashed_name

- name: assert name2int
  debug:
    msg: "{{ hashed_name.int_value  }}"

- name: assert name2int
  assert:
    that:
      - hashed_name.int_value == 20